# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-08 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_acc', models.EmailField(default='', max_length=255, unique=True, verbose_name='계정명(이메일 형태)')),
                ('username', models.CharField(default='', max_length=20, verbose_name='닉네임')),
                ('user_profile_img', models.ImageField(default='/upload_files/profile/default.png', upload_to='profile', verbose_name='프로필 사진')),
                ('user_status', models.SmallIntegerField(choices=[(1, '정상'), (2, '임시'), (3, '휴면'), (4, '탈퇴')], default=2, verbose_name='계정상태')),
                ('user_age', models.SmallIntegerField(choices=[(1, '10대'), (2, '20대'), (3, '30대'), (4, '40대이상')], default=2, verbose_name='나이')),
                ('user_gender', models.SmallIntegerField(choices=[(1, '남'), (2, '여')], default=2, verbose_name='성별')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
