# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-08 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_profile_img',
            field=models.ImageField(default='profile/default.png', upload_to='profile', verbose_name='프로필 사진'),
        ),
    ]
