# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-06 14:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20170806_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='users', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
